name: myapp                   # The name of this app. Must be unique within a project.
toolstack: "php:symfony"      # We choose php:symfony for anything but Drupal
document_root: "/"
relationships:                # Here we say we want access to a mysql instance we call "main_db"
    database: "mysql:mysql"
disk: 2048