database:
    type: mysql
    disk: 200
moardatabase:
    type: postgresql
    disk: 200
search:
    type: solr
    disk: 200
moarsearch:
    type: elasticsearch
    disk: 200
cache:
    type: redis
    disk: 200
moarcache:
    type: memcache
    disk: 200
mongo:
    type: mongodb
    disk: 200